login: &login
  adapter: postgresql
  host: localhost
  username: 
  password: 
  pool: 5
  encoding: unicode


development:
    database: prelaunch_development
    <<: *login

   
test:
   database: prelaunch_test
   <<: *login

production:
  database: prelaunch_production
  <<: *login
  